### ISSUE TITLE
关于和cpplint报告的兼容问题

### ISSUE THREAD

**Issue by margartiaville** [skullboyer/code-check#2]
你好，
我们这一直用cpplint生成emacs报告，
然后用cpplint-junit转成xml格式，
再用junit2html生成html。

但是切换到lint后，生成的emacs格式不兼容，无法转成junit的xml格式。
请问有什么解决办法吗？

谢谢

**Comment by skullboyers** [comment]
![image](https://github.com/skullboyer/code-check/assets/40754560/af35d556-7bbe-48f0-97f9-5af2d0b6b0e6)
![image](https://github.com/skullboyer/code-check/assets/40754560/95fd550a-9420-4ebc-bdaa-da64fb6441f2)
对比了lint个cpplint生成的emacs报告，格式没有变化，在实现lint时也没有修改输出信息格式

**Comment by skullboyers** [comment]
![image](https://github.com/skullboyer/code-check/assets/40754560/44f79e8d-4d8d-4cf7-b287-28bf77c80a94)
刚下载了最新版的cpplint_juint，转换了lint与cpplint的检查结果，没发现什么问题

**Comment by margartiaville** [comment]
谢谢，是我配置的问题，不好意思
